baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "debgoswami.github.io" # the base hostname & protocol for your site.
title: "Deb Goswami's AI Musings"
name: "Deb Goswami"


paginate: 6 #articles per page
paginate_path: /blog/page:num #makes pagination working

#contacts
git: "https://github.com/debgoswami"  #your github url here.

#disqus comment
disqus:
    shortname: "" #your disqus comment short name

#google analytics
google:
    tracking-id: "" #your tracking id here

gems:
  - jekyll-sitemap
  - jekyll-paginate

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"

permalink: /posts/:title

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
