baseurl = "http://www.demystify.ai"
#title = '<img src="/img/main/demystify_banner.png"></img>'
title = "demystify.ai"
#theme = "hugo-nederburg-theme"
theme = "casper3"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination

[privacy]
  # Google Analytics privacy settings - https://gohugo.io/about/hugo-and-gdpr/index.html#googleanalytics
  [privacy.googleAnalytics]
    # set to true to disable service 
    disable = true
    # set to true to meet General Data Protection Regulation (GDPR)
    anonymizeIP = false
    respectDoNotTrack = false
    useSessionStorage = false

[params]
  #logo = "/img/main/demystify_banner.png"
  background = "gray"
  # Unmark to use post folder for images. Default is static folder.
  #usepostimgfolder = true
  slogan = "Make things as simple as possible, but not simpler"
  description = "Thoughts, stories and ideas spanning a career in enabling AI and Machine Learning for enterprise" # meta description
  # You need to set author to have an author bio. If you have a writer in the markdown file it will override this.
  author = "Deb Goswami"
  authorLink = "http://www.demystify.ai"
  bio = [
    ""
  ]
  copyright = [
    "&copy; {{ < .date 2020 > }} Deb Goswami. All rights reserved",
  ]


  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below (it is also used in Gravatar for the bio).
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "deb.goswami@outlook.com"

  # Nav links in the side bar
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "About"
  url = "about/"
  weight = 2

  [[menu.main]]
  name = "Get in touch"
  url = "contact/"
  weight = 3

# this will also be in author bio if there is no writer.
  [params.social]
  #facebook      = "full Social profile url in facebook"
  email         = "deb.goswami@outlook.com"
  twitter       = "https://twitter.com/drehsil"
  linkedin      = "https://linkedin.com/in/debgoswami"
  stackoverflow = "full profile url in stackoverflow"
  github        = "https://github.com/debgoswami"
  rss           = false

