#+TITLE:Dreams Of A Ninja
#+DATE: 2020-06-09
#+draft: true

* Dreams of a Ninja

I’m standing on the balcony. It’s a cloudy night, and you can see nothing but that which is revealed by the lights strewn across the nightscape. As I gaze upon the beauty below me, a steady, soothing breeze brushes past, wrapping me up in its serenity. I cannot help but feel calmer. In the distance, to my right, I hear the sea rushing to her perpetual battle with the shore. There will be no victor tonight.

Suddenly the night-sky is ripped apart by the bright, whiteness of lightning atop the clouds. It seems like the heavens too are fighting their own wars tonight. Surprised, but not startled, I await the inevitable roar of thunder. It does not come. Not so inevitable then, perhaps.

Is the lightning too far away, I wonder. It does not matter.

I look back to the city around me.

I am offered hints of the main avenue with it’s bright orange streetlights. The view obscured by the silhouettes of flats, houses, villas, mansions and shops in-between. To my left, a few high-rise office blocks. Holidays aside, they are filled with starched collars and big ambitions. It is not that late at night, and already the sleepy silence of an island at peace has settled in.

From my vantage point up here, I choose to ignore everything around me but the tiled courtyard below. From my vantage point up here, I see a tree. An ancient, gnarled specimen draping parts of the courtyard with its leaves. Are those candles on the wall behind the foliage? I do not mind that they are partially hidden – it only adds to the ethereal other-worldliness of it all.

Black and orange and green. Blackness for the shadows where light dare not reach. The flickering orange of the lamps, as if to say – We are here but to show the way. Do not seek what we hide from your gaze! Their quest aided by the green leaves which emerge from the darkness.

And suddenly I have this urge. I need to...No, I have to  jump.

That’s right. I want to hurtle down onto the rooftop, somersaulting in the air and landing with my gloved fingertips resting lightly on its surface. My padded knees and oilskin boots masking the audible evidence of this superhuman feat. As I land, the katana on my back forces me to roll once, twice, thrice till I am crouching in the embrace of my botanical ally.

Tonight I slay the warlord. His guards must not see me. They will not know I am gone. Tonight I end his evil reign. Or am I simply doing this at the bidding of the deepest pockets? It matters not. For a while, the unfettered, uncomplicated will of a shinobi tasked with orders fills me.

Soon the lights behind me will turn on and I shall return to my world. A new, equally exciting journey awaits me. It will not be easy. I must conquer. But that is a tale for another time…
