#+TITLE: Occam's Smile
#+draft: true

Life’s not so bad sometimes.

It’s been 10 months since I picked you up for the first time, cradling you in my arms hoping that I wasn’t hurting you in any way. It was a pretty strange feeling. How do I explain it to you in a way you’d understand - though sometimes I wonder what your precocious little head doesn’t understand already! Hmmm…ok, try this. Next time you’re drinking some water when you’re really really thirsty. Fill up the glass alllll the way to the brim. Just before the water starts spilling. Then try to take a sip without moving your head down and bringing the glass to your lips. Tough right? Now multiply that feeling by the biggest number you can think of and you’re nearly there.

Did you know that we cried with you, your mum and I, when you announced yourself into the world? I was right beside mummy, holding her hand while you were fighting so so hard to get out to us and say hello. When we heard that first cry, we literally whooped - tears streaming down our cheeks. It felt like an eon and a family ago since I rushed your mum into the labor ward, not daring to believe that it was really, finally time. I probably say this a lot to you, but it’s worth repeating - I love you.

It’s been a tough few weeks recently. Nothing major you see, just work and stuff. But people are so good at forgetting that change is the only constant. Every time we encounter potential uncertainty, we ratchet up our stress levels. Forgetting that a smooth ride is an indication that the wheels grip the road firmly - a feat that is made possible if the friction is strong.

You’re still a teeny tot right now. You smile when I come home, jumping with glee and scooting over in that adorable bum-wiggly crawl that you have. Just a couple of weeks ago, you started hugging me back. Your tiny plump arms trying valiantly to grab as much of me as you can, chin tucked under my neck. Oh you’ve always been such a cutie Raya!

But now we come to the story that I’m really trying to tell you. A few days ago, you rediscovered my watch. Remember that smart-watch I used to wear every day for the longest time? The one with the rotating dial? Yea, that one.
You were on my lap, merrily poking away at my chest. Hunting for the world’s biggest treasure under my shirt logo I’m sure. Suddenly, I turned my wrist over to peek at the time and you followed my gaze. “Ooooooh - what’s this shiny new thing!” Your eyes seemed to say as you perked up and look at me.

We had just found the world’s best game! It had 3 simple steps.

Step 1 - I would have to twist my wrist, or fiddle with the watch so that the display would come on. If there was any delay, you had the right to voice your displeasure. Usually delivered via an indignant squeal at me and a few taps on my arm (hurry up dad!).

Step 2 - Then you’d take your dainty, puchki little fingers and swipe the screen so that something, anything, would change on the screen.
And that’s when the moment would happen. You’d look at me, and give me the happpppppiest, proudest smile EVER. I’m pretty sure I was grinning back like a maniac!

Step 3 - The end-game. We had to clap together, and maybe a few high-fives to round things off.

You could do this all day. Strangely, I’m certain I could too…

I’m rediscovering the world with you Raya. I see you gaze at things. Things I’d even forgotten were things! And your smile. That smile reflecting such explicit delight and wonder. Suddenly life’s quite simple. Suddenly life’s pretty good.
Soon enough you’ll ask me your first question - I wonder what it’ll be. I do know how I’ll end the answer though - I love you Raya.
#story #non-fiction #journal

